name: File Categotizer
description: Move files in the Download Folder to their appropriate Folder

version: 1.0

track: '' # Add Folder to track
dst_path: '' # Add The Home page or Path to a folder

# You can add formats and path to save your file
content_path:
    .mp3: 'Music'
    .mp4: 'Videos'
    .mkv: 'Videos'
    .pdf: 'Documents'
    .jpeg: 'Pictures'
    .jpg: 'Pictures'
    .png: 'Pictures'